### ISSUE TITLE
Does it run when app is closed?

### ISSUE THREAD

**Issue by AwsomeCode** [aritchie/jobs#1]
This may be stupid questions. 
1. But does it run in background when app is closed?
2. If yes. Can I access SQLite database as well?
3. And Can I do HTTPClient call?

Thanks.

**Comment by aritchie** [comment]
It is a job framework, you can run whatever you want for the most part.  It is called "Background Jobs". 

Please be respectful of time in future requests
1) follow the issue template
2) review the code and documentation before filing
3) Use this form for defects & feature requests only
