### ISSUE TITLE
[Android] Dependency on sqlite-net-pcl 1.5.231 

### ISSUE THREAD

**Issue by DanielCauser** [aritchie/jobs#4]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] tvOS
 - [ ] macOS
 - [ ] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
8.0 (API 26)

## Version of Library
1.1.1

## Expected Behaviour
Android App should run the scheduled jobs.

## Actual Behavior
When running my Android application I get the following exception:

> {System.MissingMethodException: void SQLite.SQLiteConnectionString..ctor(string,bool,object)
>   at Plugin.Jobs.Infrastructure.SqliteJobRepository..ctor () [0x00000] in C:\dev\acr\jobs\Plugin.Jobs\Infrastructure\SqliteJobRepository.cs:11 
>   at Plugin.Jobs.AbstractJobManager..ctor (Plugin.Jobs.IJobRepository repository, Plugin.Jobs.IJobFactory factory) [0x00006] in C:\dev\acr\jobs\Plugin.Jobs\AbstractJobManager.cs:15 
>   at Plugin.Jobs.JobManagerImpl..ctor (Plugin.Jobs.IJobRepository repository, Plugin.Jobs.IJobFactory factory) [0x00000] in C:\dev\acr\jobs\Plugin.Jobs\Platforms\Android\JobManagerImpl.cs:10 
>   at Plugin.Jobs.CrossJobs..cctor () [0x0001a] in C:\dev\acr\jobs\Plugin.Jobs\Platforms\Android\CrossJobs.cs:14 }

> [MonoDroid] UNHANDLED EXCEPTION:
> [MonoDroid] System.TypeInitializationException: The type initializer for 'Plugin.Jobs.CrossJobs' threw an exception. ---> System.MissingMethodException: void SQLite.SQLiteConnectionString..ctor(string,bool,object)
> [MonoDroid]   at Plugin.Jobs.Infrastructure.SqliteJobRepository..ctor () [0x00000] in C:\dev\acr\jobs\Plugin.Jobs\Infrastructure\SqliteJobRepository.cs:11 
> [MonoDroid]   at Plugin.Jobs.AbstractJobManager..ctor (Plugin.Jobs.IJobRepository repository, Plugin.Jobs.IJobFactory factory) [0x00006] in C:\dev\acr\jobs\Plugin.Jobs\AbstractJobManager.cs:15 
> [MonoDroid]   at Plugin.Jobs.JobManagerImpl..ctor (Plugin.Jobs.IJobRepository repository, Plugin.Jobs.IJobFactory factory) [0x00000] in C:\dev\acr\jobs\Plugin.Jobs\Platforms\Android\JobManagerImpl.cs:10 
> [MonoDroid]   at Plugin.Jobs.CrossJobs..cctor () [0x0001a] in C:\dev\acr\jobs\Plugin.Jobs\Platforms\Android\CrossJobs.cs:14 
> [MonoDroid]    --- End of inner exception stack trace ---
> [MonoDroid]   at HOK_App.Services.JobSchedulerService.ScheduleJobs () [0x00026] in /Users/danielcauser/Projects/HOK/HOK_App/HOK_App/HOK_App/Services/JobSchedulerService.cs:16 
> [MonoDroid]   at HOK_App.App+<OnInitialized>d__2.MoveNext () [0x00026] in /Users/danielcauser/Projects/HOK/HOK_App/HOK_App/HOK_App/App.xaml.cs:32 
> [MonoDroid] --- End of stack trace from previous location where exception was thrown ---
> [MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
> [MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
> [MonoDroid]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <263adecfa58f4c449f1ff56156d886fd>:0 
> [MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <263adecfa58f4c449f1ff56156d886fd>:0 
> [MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <263adecfa58f4c449f1ff56156d886fd>:0 
> [MonoDroid]   at (wrapper dynamic-method) System.Object.4382d5a9-cc9f-4b1e-9be4-8db745d196c2(intptr,intptr)

I also had issues with it on Monkey Cache and found this [bug](https://github.com/jamesmontemagno/monkey-cache/issues/38) reported in it's library.

I checked on iOS and it is working fine.

**Comment by aritchie** [comment]
The library does have a dependency on 1.5.231.  It looks like you may have 1.4 dependency bleeding through somewhere.  Does your droid project use packages.config or Csproj?

**Comment by DanielCauser** [comment]
Hey @aritchie, the Droid Project is using .csproj, it is an app I created a couple of weeks ago.

I tried to search for any explicit reference from 1.4, I happen to be using Plugin.Notification vs4.0.2 which happens to have a dependency on sqlite-net-pcl (>= 1.4.118)

**Comment by DanielCauser** [comment]
Updating the Plugin.Notification to Latest beta3 release updated the qlite-net-pcl dependency and I guess it stoped bleeding! Problem solved!
