### ISSUE TITLE
Making HttpCall from Task which is not running on Regular interval

### ISSUE THREAD

**Issue by vishalpachori25** [aritchie/jobs#7]
## Please check all of the platforms you are having the issue on (if the platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Android Version 9 
iOS version 12.1

## Version of Library

Version 2.0

## Expected Behaviour
Created a Job and schedule it at every app start but when the app goes in the background it is not running at a regular interval (i.e. about 10 min in Android). It is not running at all both in Android and iOS

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
The task should make Http call every 10 - 20 mins in Android at least. In iOS my task is just making a call it is less than 30 seconds but the same issue in iOS also.

Already Check the source code for Android it is using JobService but not working in the latest version Don't know why?
Is there anything I am missing or missing in Android setup guide for the latest version of your plugin?
Checked logs from "CrossJobs.Current.GetLogs()"  also Task have status "Started" only.

Sometimes I get this error:-
"System.NullReferenceException: Object reference not set to an instance of an object\n  at Plugin.Jobs.AbstractJobManager+<RunJob>d__25.MoveNext () [0x00070] in <000912b4e06b48f195fffee1eb451875>:0 "

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You have to give me some sort of reproducible example and/or the entire stack trace of that error.   Is the null reference exception on both Android & iOS?

If the jobs are starting, but not finishing, there is usually an error in the job itself.

**Comment by aritchie** [comment]
No reply - closing
