### ISSUE TITLE
Periodic tasks do not work.

### ISSUE THREAD

**Issue by KSemenenko** [aritchie/jobs#8]
I created a periodic task that should show notification.
But it is executed only once. after this call does not occur.
I took the latest version from nuget

**Comment by aritchie** [comment]
Please respectful and fill out the issue template so I have some idea of what may be going on.

**Comment by KSemenenko** [comment]
- [x] Android

## Version of OS(s) listed above with issue
Android 7.1

## Version of Library
2.0

It seems that it works once per hour.
I still watch

**Comment by aritchie** [comment]
As a professional developer, when a customer tells you "it doesn't work" - how frustrating is it when you get an issue like that with absolutely zero details? 

SourceLink is enabled on this library.

**Comment by KSemenenko** [comment]
In general, I do not see any or errors. I did this:
``` cs
 var job = new JobInfo
            {
                Name = nameof(BackgroundSyncJob),
                Type = typeof(BackgroundSyncJob),

                // these are criteria that must be met in order for your job to run
                BatteryNotLow = true,
                DeviceCharging = false,
                RequiredNetwork = NetworkType.Any,
                Repeat = true //defaults to true, set to false to run once OR set it inside a job to cancel further execution
            };

            CrossJobs.Current.Schedule(job);
```
I do this every time I open MainPage

After about a few minutes after the application was completed, the task was completed, but that's all. 
An hour passed and more task was not performed.
In your code, I found that the task should run every 10 minutes. but this is not happening.

``` cs
public Task Run(JobInfo jobInfo, CancellationToken cancelToken)
{
            CrossLocalNotifications.Current.Show(DateTime.Now.ToString(), "Sync strted");
            jobInfo.Repeat = true;
            return Task.CompletedTask;
}
```

**Comment by aritchie** [comment]
Not should, it tries to run when it can.  This becomes even more apparent on iOS where you get almost no say on when it runs - just that it will run at some point.  You shouldn't assume tasks are going to run in some set schedule.  Doze gets involved occasionally and screws things up.  The fact that it is running, means everything is likely fine, but there is a job log you can look at from the IJobManager.GetLogs

**Comment by KSemenenko** [comment]
The last task was completed at 11 am I have UTC +2, so that's right. as I wrote job, it is done once after the application is closed and it doesn’t work anymore.

**Comment by aritchie** [comment]
I use the job manager on android - it does have a receive on boot complete target, but there is nothing special I do beyond that.  If you are killing the app (dropping debug), there is a chance it is dropping the services.

**Comment by KSemenenko** [comment]
although the application is compiled in debug. but after debugging, I specifically launch it, and then close it. without VS

**Comment by KSemenenko** [comment]
by the way, what do these parameters mean
1. BatteryNotLow = true
2. DeviceCharging = false,

First, I understand that the battery should be charged
and second?
Is this when the phone is charging? or when not charged?
what does the second flag mean?

**Comment by KSemenenko** [comment]
as I said, the last time a regular task was launched a few hours ago, it can be seen in the log. there were no other tasks after this

**Comment by aritchie** [comment]
BatteryNotLow is for battery > 20%.  DeviceCharging is the device is plugged in.

Are you creating an application file and calling CrossJobs.Init?

**Comment by KSemenenko** [comment]
What do you mean by creating an application? I added CrossJobs.Init as you have in the documentation.
``` cs
//MainApplication.cs
 public override void OnCreate()
        {
            CrossJobs.Init(this);
            CrossCurrentActivity.Current.Init(this);
            base.OnCreate();
            
            RegisterActivityLifecycleCallbacks(this);
        }
```

**Comment by aritchie** [comment]
Yes that.  I'm just trying to get as much info as I can.  You'll need to provide a reproducible sample at this point as I'm not sure what the problem could be.

**Comment by KSemenenko** [comment]
But now the task has started. very interesting behavior.

**Comment by aritchie** [comment]
You have to send a small reproducible sample, but not an entire app.

**Comment by aritchie** [comment]
But if it is working now? - I’m going to assume other things are in play here.

**Comment by KSemenenko** [comment]
while it seems to me that it works during a power change. More precisely, after starting the application, and then when connecting-disconnecting charging. I will create a project tomorrow and send it.

**Comment by KSemenenko** [comment]
```
BatteryNotLow = true,
DeviceCharging = true,
RequiredNetwork = NetworkType.Any,
Repeat = true
```

On this configuration tasks work when charging is connected.
the charge level of the phone is 78 percent

**Comment by KSemenenko** [comment]
@aritchie I sent the project

**Comment by aritchie** [comment]
@KSemenenko This is an entire app - I told you I would look at small reproducible.  This has all of the noise around it - I'm not debugging all the way through your code.  You also keep giving me a wad of different use cases.  Stick to one issue!

The above one - DeviceCharging = true - the job will only run when the device is plugged in, so it is behaving as designed.   

So - I'm confused, is this working as expected? If not, what specific use-case is not working?

**Comment by KSemenenko** [comment]
I made and launched a clean application and it works as expected.
I have a suspicion that my problem is related to the fact that I use appcenter and push notifications. maybe it all somehow conflicts.
I will check your suggestion.

**Comment by aritchie** [comment]
Thank you - that is helpful.  If you find there is a conflict with appcenter, it is likely with the push notifications, please let me know.  I'm happy to try to fix it once I know what I'm up against.

iOS uses method swizzling which may cause issues as well (you just won't see them)

**Comment by KSemenenko** [comment]
It seems to be all right, it seems I had a bad configured job. 
Thank you and your answers and patience :)
